import React from 'react'
import { useGet } from 'restful-react'
import { Button } from '@material-ui/core'

// Generated by https://quicktype.io

export interface Posts {
  userId: number
  id: number
  title: string
  body: string
}

export default () => {
  const { data, loading, error, refetch } = useGet<Posts[], any, void>(
    'https://jsonplaceholder.typicode.com/posts'
  )

  if (error) {
    return (
      <div style={{ minHeight: '100vh', display: 'grid', placeItems: 'center' }}>
        <Button onClick={() => refetch()} variant='contained' color='primary'>
          Refetch
        </Button>
      </div>
    )
  }

  if (loading || !data) {
    return (
      <div style={{ minHeight: '100vh', display: 'grid', placeItems: 'center' }}>
        <div style={{ width: 50, height: 50, background: 'red', borderRadius: '50%' }} />
      </div>
    )
  }

  const renderData = () =>
    data.map((item) => (
      <pre key={item.id} style={{ maxWidth: '90vw', overflow: 'auto' }}>
        {JSON.stringify(item, null, 2)}
      </pre>
    ))

  return (
    <div style={{ minHeight: '100vh', display: 'grid', placeItems: 'flex-start' }}>
      {renderData()}
    </div>
  )
}
